# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec_course',
            name='chapter_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rec_course',
            name='section_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
